version: '3.8'

services:
  brick-x-trae:
    image: traefik:v2.9
    container_name: brick-x-trae
    ports:
      - "0.0.0.0:17100:17100"
      - "0.0.0.0:17109:17109"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - brick-x-network
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --api.dashboard=true
      - --entrypoints.traefik.address=:17109
      - --entrypoints.web.address=:17100
      - --log.level=DEBUG
      - --accesslog=true
    labels:
      # Dashboard router
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=PathPrefix(`/`)"
      - "traefik.http.routers.dashboard.entrypoints=traefik"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      # JWT forwardAuth
      - "traefik.http.middlewares.dashboard-auth.forwardauth.address=http://brick-x-auth:17101/auth/authorize?scope=x/layout:write"
      - "traefik.http.middlewares.dashboard-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.dashboard-auth.forwardauth.authResponseHeaders=X-User,X-Role"
      # Gateway redirect
      - "traefik.http.routers.gateway.rule=PathPrefix(`/gateway`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.routers.gateway.middlewares=brick-x-gateway-redirect@docker"
      - "traefik.http.middlewares.brick-x-gateway-redirect.redirectregex.regex=^http://(.*):17100/gateway(.*)\$"
      - "traefik.http.middlewares.brick-x-gateway-redirect.redirectregex.replacement=http://\$1:17109\$2"
      - "traefik.http.middlewares.brick-x-gateway-redirect.redirectregex.permanent=true"
  
  brick-x-webapp:
    image: brick-x-webapp:latest
    container_name: brick-x-webapp
    ports:
      - "127.0.0.1:17107:17107"
    environment:
      - TZ=UTC
    networks:
      - brick-x-network
    depends_on:
      brick-x-auth:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:17107/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.brick-x-webapp.rule=PathPrefix(`/`)"
      - "traefik.http.routers.brick-x-webapp.entrypoints=web"
      - "traefik.http.services.brick-x-webapp.loadbalancer.server.port=17107"
      - "traefik.http.routers.brick-x-webapp.service=brick-x-webapp@docker"
      - "traefik.http.middlewares.brick-x-login-rewrite.replacepath.path=/auth/login"
      - "traefik.http.routers.brick-x-login.rule=PathPrefix(`/login`)"
      - "traefik.http.routers.brick-x-login.entrypoints=web"
      - "traefik.http.routers.brick-x-login.middlewares=brick-x-login-rewrite@docker"
      - "traefik.http.routers.brick-x-login.service=brick-x-auth@docker"
  
  brick-x-auth:
    image: brick-x-auth:latest
    container_name: brick-x-auth
    ports:
      - "127.0.0.1:17101:17101"
    environment:
      - TZ=UTC
    networks:
      - brick-x-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:17101/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.brick-x-auth.rule=PathPrefix(`/api/auth`)"
      - "traefik.http.routers.brick-x-auth.entrypoints=web"
      - "traefik.http.services.brick-x-auth.loadbalancer.server.port=17101"
      - "traefik.http.routers.brick-x-auth.service=brick-x-auth@docker"
      - "traefik.http.middlewares.brick-x-auth-stripprefix.stripprefix.prefixes=/api/auth"
      - "traefik.http.routers.brick-x-auth.middlewares=brick-x-auth-stripprefix@docker"

  brick-x-core:
    image: brick-x-core:latest
    container_name: brick-x-core
    ports:
      - "127.0.0.1:17102:17102"
    environment:
      - TZ=UTC
    networks:
      - brick-x-network
    depends_on:
      brick-x-auth:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:17102/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.brick-x-core.rule=PathPrefix(`/api/core`)"
      - "traefik.http.routers.brick-x-core.entrypoints=web"
      - "traefik.http.services.brick-x-core.loadbalancer.server.port=17102"
      - "traefik.http.routers.brick-x-core.service=brick-x-core@docker"
      - "traefik.http.middlewares.brick-x-core-stripprefix.stripprefix.prefixes=/api/core"
      - "traefik.http.routers.brick-x-core.middlewares=brick-x-core-stripprefix@docker"

  brick-x-clock:
    image: brick-x-clock:latest
    container_name: brick-x-clock
    ports:
      - "0.0.0.0:123:123/udp"
      - "127.0.0.1:17103:17103"
    environment:
      - TZ=UTC
    cap_add:
      - SYS_TIME
    networks:
      - brick-x-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:17103/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.brick-x-clock.rule=PathPrefix(`/api/clock`)"
      - "traefik.http.routers.brick-x-clock.entrypoints=web"
      - "traefik.http.services.brick-x-clock.loadbalancer.server.port=17103"
      - "traefik.http.routers.brick-x-clock.service=brick-x-clock@docker"
      - "traefik.http.middlewares.brick-x-clock-stripprefix.stripprefix.prefixes=/api/clock"
      - "traefik.http.routers.brick-x-clock.middlewares=brick-x-clock-stripprefix@docker"

networks:
  brick-x-network:
    name: brick-x-network
    driver: bridge
